name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - exercise1 # Specify the branch(es) you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Your Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }} # Your Docker Hub password (stored as GitHub secret)

    - name: Build and push Service1 image
      uses: docker/build-push-action@v4
      with:
        context: ./service1
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/service1:latest

    - name: Build and push Service2 image
      uses: docker/build-push-action@v4
      with:
        context: ./service2
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/service2:latest
